os: linux
dist: xenial
language: python

python:
  - "3.9"
  - "3.8"
  - "3.7"
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements.txt

script:
  - pytest tests
