os: linux
dist: xenial
language: python

python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover test
  - coverage xml -o report.xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r report.xml